apiVersion: apps/v1
kind: Deployment
metadata:
   name: myapp-deployment
   labels:
      tier: frontend
spec:
  template:
    metadata:
         name: httpd-frontend
         labels:
           tier: frontend
    spec: 
         containers:
          - name: httpd-container
            image: httpd:2.4-alpine
  replicas: 3
  selector:
      matchLabels:
          tier: frontend
                        